/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.fxmind.global;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
public class fxmindConstants {

  /**
   * Thrift also lets you define constants for use across languages. Complex
   * types and structs are specified using JSON notation.
   */
  public static final double GAP_VALUE = -125;

  public static final String MTDATETIMEFORMAT = "yyyy.MM.dd HH:mm";

  public static final String MYSQLDATETIMEFORMAT = "yyyy-MM-dd HH:mm:ss";

  public static final String SOLRDATETIMEFORMAT = "yyyy-MM-dd'T'HH:mm:ss'Z'";

  public static final int SENTIMENTS_FETCH_PERIOD = 100;

  public static final short FXMindMQL_PORT = (short)2011;

  public static final short AppService_PORT = (short)2012;

  public static final String JOBGROUP_TECHDETAIL = "Technical Details";

  public static final String JOBGROUP_OPENPOSRATIO = "Positions Ratio";

  public static final String JOBGROUP_EXECRULES = "Run Rules";

  public static final String JOBGROUP_NEWS = "News";

  public static final String JOBGROUP_THRIFT = "ThriftServer";

  public static final String CRON_MANUAL = "0 0 0 1 1 ? 2100";

}
